# Generated by Django 4.1.7 on 2023-03-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='creacion',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='important',
            new_name='importante',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='task',
            name='datecompleted',
        ),
        migrations.AddField(
            model_name='task',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
